add make stow
Update README.md

update readme

diff --git a/etc/Makefile b/etc/Makefile
--- a/etc/Makefile
+++ b/etc/Makefile
@@ -6,3 +6,17 @@ all:
 
 clean:
 	sudo stow --dotfiles -D --target=$(TARGET) $(PACKAGES)
+
+stow:
+	@if [ -z "$(PACKAGE)" ]; then \
+		echo "Error: Please specify a PACKAGE. Usage: make stow PACKAGE=<package_name>"; \
+		exit 1; \
+	fi
+	sudo stow --dotfiles --target=$(TARGET) $(PACKAGE)
+
+unstow:
+	@if [ -z "$(PACKAGE)" ]; then \
+		echo "Error: Please specify a PACKAGE. Usage: make unstow PACKAGE=<package_name>"; \
+		exit 1; \
+	fi
+	sudo stow --dotfiles -D --target=$(TARGET) $(PACKAGE)
